name: Deploy Showcase to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          # Clean install with package-lock update
          rm -f package-lock.json
          npm install

      - name: Build library
        run: |
          npm run build:lib
          # Ensure the library is available to the showcase app
          cd dist/ngx-translated-routes
          npm pack
          npm install -g ./*.tgz
          cd ../..

      - name: Install library in showcase
        run: |
          # Update showcase's package.json to use the globally installed package
          cd projects/ngx-translated-routes-showcase
          npm install --no-save ngx-translated-routes
          cd ../..

      - name: Build showcase app
        run: |
          npm run build:showcase -- --base-href=/ngx-translated-routes/
          
      - name: Verify build output
        run: |
          ls -la dist/ngx-translated-routes-showcase/browser
          if [ ! -d "dist/ngx-translated-routes-showcase/browser/i18n" ]; then
            echo "Manually copying i18n directory..."
            mkdir -p dist/ngx-translated-routes-showcase/browser/i18n
            cp -r projects/ngx-translated-routes-showcase/public/i18n/* dist/ngx-translated-routes-showcase/browser/i18n/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/ngx-translated-routes-showcase/browser
          branch: gh-pages
          
      - name: Output GitHub Pages URL
        run: |
          echo "============================================================="
          echo "🚀 Showcase app deployed to:"
          echo "https://klubinskak.github.io/ngx-translated-routes/"
          echo "=============================================================" 