name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - 'projects/ngx-translated-routes/**'
      - '.github/workflows/publish.yml'

jobs:
  build-and-publish:
    # Only run for repository owner
    if: github.repository_owner == 'klubinskak'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build -- ngx-translated-routes
        
      - name: Publish to npm
        run: npm publish ./dist/ngx-translated-routes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 