name: Publish to npm and GitHub

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (format: 1.0.0)'
        required: true
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Check NPM_TOKEN
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "Error: NPM_TOKEN secret is not set"
            exit 1
          fi
      
      - name: Install dependencies
        run: |
          # Remove any stale locks and install clean
          rm -f package-lock.json
          npm install
      
      - name: Update version if specified
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Get version from package.json
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.version == ''
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
      
      - name: Build library
        run: npm run build:lib
      
      - name: Verify package
        run: |
          cd dist/ngx-translated-routes
          if [ ! -f "package.json" ]; then
            echo "Error: package.json not found in dist folder"
            exit 1
          fi
          npm pack --dry-run
      
      - name: Publish to npm
        run: |
          echo "Publishing package to npm..."
          cd dist/ngx-translated-routes
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          body: |
            ## @klubinskak/ngx-translated-routes v${{ env.RELEASE_VERSION }}
            
            A powerful Angular library for managing translated routes in your application. 